// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Watch_Panel;
lv_obj_t * ui_Time_Label;
lv_obj_t * ui_Date_Label;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Weather_Label;
lv_obj_t * ui_Brand_Label;
lv_obj_t * ui_Charge_Label;
lv_obj_t * ui_Image2;
void ui_event_Next_Button1(lv_event_t * e);
lv_obj_t * ui_Next_Button1;
lv_obj_t * ui_Next1_Label;

// SCREEN: ui_Calendar_Menu
void ui_Calendar_Menu_screen_init(void);
lv_obj_t * ui_Calendar_Menu;
lv_obj_t * ui_Calendar2;
void ui_event_Back_Btutton1(lv_event_t * e);
lv_obj_t * ui_Back_Btutton1;
void ui_event_Next_Button2(lv_event_t * e);
lv_obj_t * ui_Next_Button2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Back_Label1;
void ui_event_Next_Label2(lv_event_t * e);
lv_obj_t * ui_Next_Label2;

// SCREEN: ui_Weather_Menu
void ui_Weather_Menu_screen_init(void);
lv_obj_t * ui_Weather_Menu;
void ui_event_Back_Button2(lv_event_t * e);
lv_obj_t * ui_Back_Button2;
lv_obj_t * ui_Back_Label2;
void ui_event_Next_Button3(lv_event_t * e);
lv_obj_t * ui_Next_Button3;
lv_obj_t * ui_Next_Label3;
lv_obj_t * ui_Weather_Menu_Label;
lv_obj_t * ui_Cloud_Image;
lv_obj_t * ui_City_Label;
lv_obj_t * ui_Weather_Icon;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;

// SCREEN: ui_Time_Settings_Menu
void ui_Time_Settings_Menu_screen_init(void);
lv_obj_t * ui_Time_Settings_Menu;
void ui_event_Next_Button4(lv_event_t * e);
lv_obj_t * ui_Next_Button4;
void ui_event_Back_Button3(lv_event_t * e);
lv_obj_t * ui_Back_Button3;
lv_obj_t * ui_Back_Label3;
lv_obj_t * ui_Next_Label4;
lv_obj_t * ui_Settings_Menu_Label;
lv_obj_t * ui_Hour_Roller;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Roller2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Save_Button1;
lv_obj_t * ui_Save_Label;

// SCREEN: ui_Date_Settings_Menu
void ui_Date_Settings_Menu_screen_init(void);
lv_obj_t * ui_Date_Settings_Menu;
lv_obj_t * ui_DateMenu_Label;
lv_obj_t * ui_Day_Roller;
lv_obj_t * ui_Month_Roller;
lv_obj_t * ui_Roller3;
lv_obj_t * ui_Day_Label;
lv_obj_t * ui_Month_Label;
lv_obj_t * ui_Year_Label;
lv_obj_t * ui_Save_Button2;
lv_obj_t * ui_Label7;
void ui_event_Back_Button4(lv_event_t * e);
lv_obj_t * ui_Back_Button4;
lv_obj_t * ui_Label8;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_flash[1] = {&ui_img_flash1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Next_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Calendar_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Back_Btutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Next_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Weather_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Next_Label2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Weather_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Back_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Calendar_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Next_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Time_Settings_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Next_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Date_Settings_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Back_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Weather_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Back_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Time_Settings_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Calendar_Menu_screen_init();
    ui_Weather_Menu_screen_init();
    ui_Time_Settings_Menu_screen_init();
    ui_Date_Settings_Menu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
