// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#ifndef _ST7789_GT911_LVGL_VER2_UI_H
#define _ST7789_GT911_LVGL_VER2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Watch_Panel;
extern lv_obj_t * ui_Time_Label;
extern lv_obj_t * ui_Date_Label;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Weather_Label;
extern lv_obj_t * ui_Brand_Label;
extern lv_obj_t * ui_Charge_Label;
extern lv_obj_t * ui_Image2;
void ui_event_Next_Button1(lv_event_t * e);
extern lv_obj_t * ui_Next_Button1;
extern lv_obj_t * ui_Next1_Label;
// SCREEN: ui_Calendar_Menu
void ui_Calendar_Menu_screen_init(void);
extern lv_obj_t * ui_Calendar_Menu;
extern lv_obj_t * ui_Calendar2;
void ui_event_Back_Btutton1(lv_event_t * e);
extern lv_obj_t * ui_Back_Btutton1;
void ui_event_Next_Button2(lv_event_t * e);
extern lv_obj_t * ui_Next_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Back_Label1;
void ui_event_Next_Label2(lv_event_t * e);
extern lv_obj_t * ui_Next_Label2;
// SCREEN: ui_Weather_Menu
void ui_Weather_Menu_screen_init(void);
extern lv_obj_t * ui_Weather_Menu;
void ui_event_Back_Button2(lv_event_t * e);
extern lv_obj_t * ui_Back_Button2;
extern lv_obj_t * ui_Back_Label2;
void ui_event_Next_Button3(lv_event_t * e);
extern lv_obj_t * ui_Next_Button3;
extern lv_obj_t * ui_Next_Label3;
extern lv_obj_t * ui_Weather_Menu_Label;
extern lv_obj_t * ui_Cloud_Image;
extern lv_obj_t * ui_City_Label;
extern lv_obj_t * ui_Weather_Icon;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Time_Settings_Menu
void ui_Time_Settings_Menu_screen_init(void);
extern lv_obj_t * ui_Time_Settings_Menu;
void ui_event_Next_Button4(lv_event_t * e);
extern lv_obj_t * ui_Next_Button4;
void ui_event_Back_Button3(lv_event_t * e);
extern lv_obj_t * ui_Back_Button3;
extern lv_obj_t * ui_Back_Label3;
extern lv_obj_t * ui_Next_Label4;
extern lv_obj_t * ui_Settings_Menu_Label;
extern lv_obj_t * ui_Hour_Roller;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Save_Button1;
extern lv_obj_t * ui_Save_Label;
// SCREEN: ui_Date_Settings_Menu
void ui_Date_Settings_Menu_screen_init(void);
extern lv_obj_t * ui_Date_Settings_Menu;
extern lv_obj_t * ui_DateMenu_Label;
extern lv_obj_t * ui_Day_Roller;
extern lv_obj_t * ui_Month_Roller;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Day_Label;
extern lv_obj_t * ui_Month_Label;
extern lv_obj_t * ui_Year_Label;
extern lv_obj_t * ui_Save_Button2;
extern lv_obj_t * ui_Label7;
void ui_event_Back_Button4(lv_event_t * e);
extern lv_obj_t * ui_Back_Button4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_sun_icon_png);    // assets\sun_icon.png
LV_IMG_DECLARE(ui_img_flash1_png);    // assets\flash1.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets\cloud.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets\weather.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
