// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#include "../ui.h"

void ui_Date_Settings_Menu_screen_init(void)
{
    ui_Date_Settings_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Date_Settings_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Date_Settings_Menu, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Date_Settings_Menu, lv_color_hex(0x5CA4A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Date_Settings_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateMenu_Label = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_DateMenu_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateMenu_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateMenu_Label, -9);
    lv_obj_set_y(ui_DateMenu_Label, -126);
    lv_obj_set_align(ui_DateMenu_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateMenu_Label, "Date Setting");
    lv_obj_set_style_text_color(ui_DateMenu_Label, lv_color_hex(0xE0EF18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateMenu_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateMenu_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Day_Roller = lv_roller_create(ui_Date_Settings_Menu);
    lv_roller_set_options(ui_Day_Roller,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Day_Roller, 50);
    lv_obj_set_height(ui_Day_Roller, 50);
    lv_obj_set_x(ui_Day_Roller, -65);
    lv_obj_set_y(ui_Day_Roller, -10);
    lv_obj_set_align(ui_Day_Roller, LV_ALIGN_CENTER);

    ui_Month_Roller = lv_roller_create(ui_Date_Settings_Menu);
    lv_roller_set_options(ui_Month_Roller, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Month_Roller, 50);
    lv_obj_set_height(ui_Month_Roller, 50);
    lv_obj_set_x(ui_Month_Roller, -5);
    lv_obj_set_y(ui_Month_Roller, -10);
    lv_obj_set_align(ui_Month_Roller, LV_ALIGN_CENTER);

    ui_Roller3 = lv_roller_create(ui_Date_Settings_Menu);
    lv_roller_set_options(ui_Roller3, "2023\n2024\n2025", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller3, 50);
    lv_obj_set_height(ui_Roller3, 50);
    lv_obj_set_x(ui_Roller3, 55);
    lv_obj_set_y(ui_Roller3, -10);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    ui_Day_Label = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Day_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Day_Label, -66);
    lv_obj_set_y(ui_Day_Label, -44);
    lv_obj_set_align(ui_Day_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day_Label, "Day");
    lv_obj_set_style_text_color(ui_Day_Label, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Day_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Month_Label = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Month_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Month_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Month_Label, -5);
    lv_obj_set_y(ui_Month_Label, -42);
    lv_obj_set_align(ui_Month_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Month_Label, "Month");
    lv_obj_set_style_text_color(ui_Month_Label, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Month_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Year_Label = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Year_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Year_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Year_Label, 56);
    lv_obj_set_y(ui_Year_Label, -42);
    lv_obj_set_align(ui_Year_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Year_Label, "Year");
    lv_obj_set_style_text_color(ui_Year_Label, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Year_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save_Button2 = lv_btn_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Save_Button2, 50);
    lv_obj_set_height(ui_Save_Button2, 30);
    lv_obj_set_x(ui_Save_Button2, -4);
    lv_obj_set_y(ui_Save_Button2, 47);
    lv_obj_set_align(ui_Save_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Save_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Save_Button2, lv_color_hex(0x9B1D1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -4);
    lv_obj_set_y(ui_Label7, 47);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Save");

    ui_Back_Button4 = lv_btn_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Back_Button4, 40);
    lv_obj_set_height(ui_Back_Button4, 25);
    lv_obj_set_x(ui_Back_Button4, -90);
    lv_obj_set_y(ui_Back_Button4, 118);
    lv_obj_set_align(ui_Back_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button4, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Date_Settings_Menu);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -90);
    lv_obj_set_y(ui_Label8, 118);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Back");

    lv_obj_add_event_cb(ui_Back_Button4, ui_event_Back_Button4, LV_EVENT_ALL, NULL);

}
