// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x5CA4A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Watch_Panel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Watch_Panel, 125);
    lv_obj_set_height(ui_Watch_Panel, 70);
    lv_obj_set_x(ui_Watch_Panel, 2);
    lv_obj_set_y(ui_Watch_Panel, -19);
    lv_obj_set_align(ui_Watch_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Watch_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Watch_Panel, lv_color_hex(0x0C3D51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Watch_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Watch_Panel, lv_color_hex(0x070202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Watch_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Watch_Panel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Watch_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_font(ui_Watch_Panel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Time_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label, 4);
    lv_obj_set_y(ui_Time_Label, -35);
    lv_obj_set_align(ui_Time_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Label, "10:20:38");
    lv_obj_set_style_text_font(ui_Time_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Date_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date_Label, 4);
    lv_obj_set_y(ui_Date_Label, -1);
    lv_obj_set_align(ui_Date_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date_Label, "18.06.2023");
    lv_obj_set_style_text_font(ui_Date_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Main);
    lv_img_set_src(ui_Image1, &ui_img_sun_icon_png);
    lv_obj_set_width(ui_Image1, 45);
    lv_obj_set_height(ui_Image1, 45);
    lv_obj_set_x(ui_Image1, -89);
    lv_obj_set_y(ui_Image1, 70);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Weather_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label, -35);
    lv_obj_set_y(ui_Weather_Label, 74);
    lv_obj_set_align(ui_Weather_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Label, "Sunny");
    lv_obj_set_style_text_color(ui_Weather_Label, lv_color_hex(0xB60303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brand_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Brand_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brand_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brand_Label, -80);
    lv_obj_set_y(ui_Brand_Label, -121);
    lv_obj_set_align(ui_Brand_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brand_Label, "STYRON");
    lv_obj_set_style_text_color(ui_Brand_Label, lv_color_hex(0xE7F214), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Brand_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charge_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Charge_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Charge_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Charge_Label, 95);
    lv_obj_set_y(ui_Charge_Label, -121);
    lv_obj_set_align(ui_Charge_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Charge_Label, "%86");
    lv_obj_set_style_text_color(ui_Charge_Label, lv_color_hex(0xDD1717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charge_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Main);
    lv_img_set_src(ui_Image2, &ui_img_flash1_png);
    lv_obj_set_width(ui_Image2, 9);
    lv_obj_set_height(ui_Image2, 12);
    lv_obj_set_x(ui_Image2, 71);
    lv_obj_set_y(ui_Image2, -121);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Next_Button1 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Next_Button1, 40);
    lv_obj_set_height(ui_Next_Button1, 25);
    lv_obj_set_x(ui_Next_Button1, 89);
    lv_obj_set_y(ui_Next_Button1, 118);
    lv_obj_set_align(ui_Next_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Next_Button1, lv_color_hex(0x03040D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Next_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next1_Label = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Next1_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next1_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next1_Label, 88);
    lv_obj_set_y(ui_Next1_Label, 118);
    lv_obj_set_align(ui_Next1_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Next1_Label, "Next");

    lv_obj_add_event_cb(ui_Next_Button1, ui_event_Next_Button1, LV_EVENT_ALL, NULL);

}
