// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#include "../ui.h"

void ui_Time_Settings_Menu_screen_init(void)
{
    ui_Time_Settings_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Time_Settings_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Time_Settings_Menu, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time_Settings_Menu, lv_color_hex(0x5CA4A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time_Settings_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Button4 = lv_btn_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Next_Button4, 40);
    lv_obj_set_height(ui_Next_Button4, 25);
    lv_obj_set_x(ui_Next_Button4, 87);
    lv_obj_set_y(ui_Next_Button4, 118);
    lv_obj_set_align(ui_Next_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Next_Button4, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Next_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Button3 = lv_btn_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Back_Button3, 40);
    lv_obj_set_height(ui_Back_Button3, 25);
    lv_obj_set_x(ui_Back_Button3, -90);
    lv_obj_set_y(ui_Back_Button3, 118);
    lv_obj_set_align(ui_Back_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button3, lv_color_hex(0x0C0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Label3 = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Back_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Label3, -90);
    lv_obj_set_y(ui_Back_Label3, 118);
    lv_obj_set_align(ui_Back_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Label3, "Back");

    ui_Next_Label4 = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Next_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Label4, 87);
    lv_obj_set_y(ui_Next_Label4, 118);
    lv_obj_set_align(ui_Next_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Next_Label4, "Next");

    ui_Settings_Menu_Label = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Settings_Menu_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Menu_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Menu_Label, -2);
    lv_obj_set_y(ui_Settings_Menu_Label, -125);
    lv_obj_set_align(ui_Settings_Menu_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Menu_Label, "Time Setting");
    lv_obj_set_style_text_color(ui_Settings_Menu_Label, lv_color_hex(0xE0EF18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Settings_Menu_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Settings_Menu_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour_Roller = lv_roller_create(ui_Time_Settings_Menu);
    lv_roller_set_options(ui_Hour_Roller,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Hour_Roller, 50);
    lv_obj_set_height(ui_Hour_Roller, 50);
    lv_obj_set_x(ui_Hour_Roller, -60);
    lv_obj_set_y(ui_Hour_Roller, -10);
    lv_obj_set_align(ui_Hour_Roller, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Hour_Roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Hour_Roller, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hour_Roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Hour_Roller, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Hour_Roller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Time_Settings_Menu);
    lv_roller_set_options(ui_Roller1,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 50);
    lv_obj_set_height(ui_Roller1, 50);
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, -10);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Roller2 = lv_roller_create(ui_Time_Settings_Menu);
    lv_roller_set_options(ui_Roller2,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller2, 50);
    lv_obj_set_height(ui_Roller2, 50);
    lv_obj_set_x(ui_Roller2, 60);
    lv_obj_set_y(ui_Roller2, -10);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -60);
    lv_obj_set_y(ui_Label4, -44);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Hour");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, -44);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Minute");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 60);
    lv_obj_set_y(ui_Label6, -44);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Second");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x784506), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save_Button1 = lv_btn_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Save_Button1, 50);
    lv_obj_set_height(ui_Save_Button1, 30);
    lv_obj_set_x(ui_Save_Button1, -4);
    lv_obj_set_y(ui_Save_Button1, 47);
    lv_obj_set_align(ui_Save_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Save_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Save_Button1, lv_color_hex(0x9B1D1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save_Label = lv_label_create(ui_Time_Settings_Menu);
    lv_obj_set_width(ui_Save_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Save_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Save_Label, -4);
    lv_obj_set_y(ui_Save_Label, 47);
    lv_obj_set_align(ui_Save_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Save_Label, "Save");

    lv_obj_add_event_cb(ui_Next_Button4, ui_event_Next_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Back_Button3, ui_event_Back_Button3, LV_EVENT_ALL, NULL);

}
