// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ST7789_GT911_LVGL_VER2

#include "../ui.h"

void ui_Weather_Menu_screen_init(void)
{
    ui_Weather_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Weather_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Weather_Menu, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Weather_Menu, lv_color_hex(0x5CA4A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Button2 = lv_btn_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Back_Button2, 40);
    lv_obj_set_height(ui_Back_Button2, 25);
    lv_obj_set_x(ui_Back_Button2, -90);
    lv_obj_set_y(ui_Back_Button2, 118);
    lv_obj_set_align(ui_Back_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button2, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Label2 = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Back_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Label2, -90);
    lv_obj_set_y(ui_Back_Label2, 118);
    lv_obj_set_align(ui_Back_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Label2, "Back");

    ui_Next_Button3 = lv_btn_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Next_Button3, 40);
    lv_obj_set_height(ui_Next_Button3, 25);
    lv_obj_set_x(ui_Next_Button3, 87);
    lv_obj_set_y(ui_Next_Button3, 118);
    lv_obj_set_align(ui_Next_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Next_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Next_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Next_Button3, lv_color_hex(0x110808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Next_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Label3 = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Next_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Label3, 87);
    lv_obj_set_y(ui_Next_Label3, 118);
    lv_obj_set_align(ui_Next_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Next_Label3, "Next");

    ui_Weather_Menu_Label = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Weather_Menu_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Menu_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Menu_Label, -1);
    lv_obj_set_y(ui_Weather_Menu_Label, -124);
    lv_obj_set_align(ui_Weather_Menu_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Menu_Label, "Weather ");
    lv_obj_set_style_text_color(ui_Weather_Menu_Label, lv_color_hex(0xE0EF18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Menu_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Menu_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cloud_Image = lv_img_create(ui_Weather_Menu);
    lv_img_set_src(ui_Cloud_Image, &ui_img_cloud_png);
    lv_obj_set_width(ui_Cloud_Image, 70);
    lv_obj_set_height(ui_Cloud_Image, 80);
    lv_obj_set_x(ui_Cloud_Image, 58);
    lv_obj_set_y(ui_Cloud_Image, -6);
    lv_obj_set_align(ui_Cloud_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cloud_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cloud_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_City_Label = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_City_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_City_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City_Label, -61);
    lv_obj_set_y(ui_City_Label, -69);
    lv_obj_set_align(ui_City_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_City_Label, "ISTANBUL");
    lv_obj_set_style_text_color(ui_City_Label, lv_color_hex(0xCE2222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_City_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Icon = lv_img_create(ui_Weather_Menu);
    lv_img_set_src(ui_Weather_Icon, &ui_img_weather_png);
    lv_obj_set_width(ui_Weather_Icon, 30);
    lv_obj_set_height(ui_Weather_Icon, 30);
    lv_obj_set_x(ui_Weather_Icon, -86);
    lv_obj_set_y(ui_Weather_Icon, 0);
    lv_obj_set_align(ui_Weather_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -41);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Sunny");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x110303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Weather_Menu);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -53);
    lv_obj_set_y(ui_Label3, 34);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "30°C");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xC61919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Back_Button2, ui_event_Back_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Next_Button3, ui_event_Next_Button3, LV_EVENT_ALL, NULL);

}
